name: CI

on:
  
  push:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build
          ls -ltr

      - name: SonarCloud Analysis
        run: |
          chmod +x gradlew 
          ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD_MICROSERVICIO }}

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name : Copia de Jar a Raiz de proyecto
        run: |
          cp $GITHUB_WORKSPACE/build/libs/microservicio-java-2.6.0.jar .
          chmod 777 microservicio-java-2.6.0.jar
          ls -lt
          
      - name: Docker Build
        run: |
          docker build --tag pastrian/microservicio-java:latest .
          docker image

      - name: Docker push
        run : |
          docker push pastrian/microservicio-java
